<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <RootNamespace>DijitalAtolye.BuildingBlocks.Common</RootNamespace>
    <AssemblyName>DijitalAtolye.BuildingBlocks.Common</AssemblyName>
    <GenerateDocumentationFile>true</GenerateDocumentationFile>
  </PropertyGroup>

  <ItemGroup>
    <FrameworkReference Include="Microsoft.AspNetCore.App" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="OneOf" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.Relational" />
  </ItemGroup>
</Project>
