<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <RootNamespace>DijitalAtolye.BuildingBlocks.EventBus</RootNamespace>
    <AssemblyName>DijitalAtolye.BuildingBlocks.EventBus</AssemblyName>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\Common\DijitalAtolye.BuildingBlocks.Common.csproj" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="MassTransit" />
    <PackageReference Include="MassTransit.RabbitMQ" />
    <PackageReference Include="MassTransit.EntityFrameworkCore" />
  </ItemGroup>
</Project>
