import { jsx as _jsx, jsxs as _jsxs } from "react/jsx-runtime";
import { Navigate, Route, Routes } from "react-router-dom";
import PublicLayout from "@/layouts/PublicLayout";
import AppLayout from "@/layouts/AppLayout";
import LoginPage from "@/pages/LoginPage";
import RegisterPage from "@/pages/RegisterPage";
import ForgotPasswordPage from "@/pages/ForgotPasswordPage";
import ResetPasswordPage from "@/pages/ResetPasswordPage";
import HomePage from "@/pages/HomePage";
import AboutPage from "@/pages/AboutPage";
import NotFoundPage from "@/pages/NotFoundPage";
import TeacherUploadPage from "@/pages/teacher/TeacherUploadPage";
import TeacherUploadWizard from "@/pages/teacher/TeacherUploadWizard";
import TeacherDashboardPage from "@/pages/teacher/TeacherDashboardPage";
import TeacherMyContentsPage from "@/pages/teacher/TeacherMyContentsPage";
import TeacherProfilePage from "@/pages/teacher/TeacherProfilePage";
import CollectionsPage from "@/pages/teacher/CollectionsPage";
import EditorQueuePage from "@/pages/editor/EditorQueuePage";
import EditorReviewPage from "@/pages/editor/EditorReviewPage";
import EditorDashboardPage from "@/pages/editor/EditorDashboardPage";
import EditorHistoryPage from "@/pages/editor/EditorHistoryPage";
import PlayPage from "@/pages/PlayPage";
import NotificationsPage from "@/pages/NotificationsPage";
import DiscoverPage from "@/pages/DiscoverPage";
import CategoryPage from "@/pages/CategoryPage";
import ContentDetailPage from "@/pages/ContentDetailPage";
import AdminDashboardPage from "@/pages/admin/AdminDashboardPage";
import AdminAuditPage from "@/pages/admin/AdminAuditPage";
import AdminUsersPage from "@/pages/admin/AdminUsersPage";
import AdminContentsPage from "@/pages/admin/AdminContentsPage";
import AdminCatalogPage from "@/pages/admin/AdminCatalogPage";
import AdminAiConfigPage from "@/pages/admin/AdminAiConfigPage";
import AdminReportsPage from "@/pages/admin/AdminReportsPage";
import KvkkPage from "@/pages/KvkkPage";
import AccountDeletePage from "@/pages/AccountDeletePage";
import { useAuthStore } from "@/state/auth";
export default function App() {
    const accessToken = useAuthStore((s) => s.accessToken);
    return (_jsxs(Routes, { children: [_jsxs(Route, { element: _jsx(PublicLayout, {}), children: [_jsx(Route, { path: "/", element: _jsx(HomePage, {}) }), _jsx(Route, { path: "/about", element: _jsx(AboutPage, {}) }), _jsx(Route, { path: "/login", element: _jsx(LoginPage, {}) }), _jsx(Route, { path: "/register", element: _jsx(RegisterPage, {}) }), _jsx(Route, { path: "/forgot-password", element: _jsx(ForgotPasswordPage, {}) }), _jsx(Route, { path: "/reset-password", element: _jsx(ResetPasswordPage, {}) }), _jsx(Route, { path: "/discover", element: _jsx(DiscoverPage, {}) }), _jsx(Route, { path: "/category/:subject", element: _jsx(CategoryPage, {}) }), _jsx(Route, { path: "/contents/:slug", element: _jsx(ContentDetailPage, {}) }), _jsx(Route, { path: "/play/:slug", element: _jsx(PlayPage, {}) }), _jsx(Route, { path: "/kvkk", element: _jsx(KvkkPage, {}) })] }), _jsxs(Route, { element: accessToken ? _jsx(AppLayout, {}) : _jsx(Navigate, { to: "/login", replace: true }), children: [_jsx(Route, { path: "/teacher", element: _jsx(Navigate, { to: "/teacher/dashboard", replace: true }) }), _jsx(Route, { path: "/teacher/dashboard", element: _jsx(TeacherDashboardPage, {}) }), _jsx(Route, { path: "/teacher/contents", element: _jsx(TeacherMyContentsPage, {}) }), _jsx(Route, { path: "/teacher/contents/new", element: _jsx(TeacherUploadPage, {}) }), _jsx(Route, { path: "/teacher/contents/wizard", element: _jsx(TeacherUploadWizard, {}) }), _jsx(Route, { path: "/teacher/profile", element: _jsx(TeacherProfilePage, {}) }), _jsx(Route, { path: "/teacher/collections", element: _jsx(CollectionsPage, {}) }), _jsx(Route, { path: "/editor", element: _jsx(EditorDashboardPage, {}) }), _jsx(Route, { path: "/editor/queue", element: _jsx(EditorQueuePage, {}) }), _jsx(Route, { path: "/editor/review/:id", element: _jsx(EditorReviewPage, {}) }), _jsx(Route, { path: "/editor/history", element: _jsx(EditorHistoryPage, {}) }), _jsx(Route, { path: "/notifications", element: _jsx(NotificationsPage, {}) }), _jsx(Route, { path: "/admin", element: _jsx(AdminDashboardPage, {}) }), _jsx(Route, { path: "/admin/contents", element: _jsx(AdminContentsPage, {}) }), _jsx(Route, { path: "/admin/users", element: _jsx(AdminUsersPage, {}) }), _jsx(Route, { path: "/admin/catalog", element: _jsx(AdminCatalogPage, {}) }), _jsx(Route, { path: "/admin/audit", element: _jsx(AdminAuditPage, {}) }), _jsx(Route, { path: "/admin/ai", element: _jsx(AdminAiConfigPage, {}) }), _jsx(Route, { path: "/admin/reports", element: _jsx(AdminReportsPage, {}) }), _jsx(Route, { path: "/account/delete", element: _jsx(AccountDeletePage, {}) })] }), _jsx(Route, { path: "*", element: _jsx(NotFoundPage, {}) })] }));
}
