global:
  scrape_interval: 15s

scrape_configs:
  - job_name: dijitalatolye-services
    metrics_path: /metrics
    static_configs:
      - targets:
          - identity:8080
          - user:8080
          - catalog:8080
          - storage:8080
          - content:8080
          - review:8080
          - notification:8080
          - search:8080
          - analytics:8080
          - aimoderation:8080
          - admin:8080
          - gateway:8080
