blank_issues_enabled: false
contact_links:
  - name: Mimari Soru
    url: https://github.com/dijitalatolye/dijitalatolye/discussions
    about: Mimari/teknoloji tartışmaları için Discussions kullanın.
